services:
  - type: web
    name: webdesire-facial-recognition
    env: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
